name = "Germany"
image = "germany.png"
regions = ["northwest", "northeast", "west", "east", "southwest", "southeast"]

[[cities]]
id = "flensburg"
name = "Flensburg"
region = "northwest"
x = 0.3981
y = 0.0433

[[cities]]
id = "kiel"
name = "Kiel"
region = "northwest"
x = 0.4498
y = 0.1008

[[cities]]
id = "hamburg"
name = "Hamburg"
region = "northwest"
x = 0.4466
y = 0.1952

[[cities]]
id = "bremen"
name = "Bremen"
region = "northwest"
x = 0.3486
y = 0.2514

[[cities]]
id = "hannover"
name = "Hannover"
region = "northwest"
x = 0.4512
y = 0.3374

[[cities]]
id = "dortmund"
name = "Dortmund"
region = "west"
x = 0.2338
y = 0.4538

[[cities]]
id = "duisburg"
name = "Duisburg"
region = "west"
x = 0.0831
y = 0.4105

[[cities]]
id = "essen"
name = "Essen"
region = "west"
x = 0.1444
y = 0.4253

[[cities]]
id = "duesseldorf"
name = "Düsseldorf"
region = "west"
x = 0.0989
y = 0.4816

[[cities]]
id = "koeln"
name = "Köln"
region = "southwest"
x = 0.1643
y = 0.5258

[[cities]]
id = "aachen"
name = "Aachen"
region = "southwest"
x = 0.0663
y = 0.5447

[[cities]]
id = "muenster"
name = "Münster"
region = "west"
x = 0.2172
y = 0.3857

[[cities]]
id = "osnabrueck"
name = "Osnabrück"
region = "west"
x = 0.2735
y = 0.3285

[[cities]]
id = "kassel"
name = "Kassel"
region = "west"
x = 0.4038
y = 0.4652

[[cities]]
id = "frankfurt"
name = "Frankfurt"
region = "southwest"
x = 0.3428
y = 0.5978

[[cities]]
id = "wiesbaden"
name = "Wiesbaden"
region = "southwest"
x = 0.2845
y = 0.6184

[[cities]]
id = "trier"
name = "Trier"
region = "southwest"
x = 0.1071
y = 0.6544

[[cities]]
id = "saarbruecken"
name = "Saarbrücken"
region = "southwest"
x = 0.1959
y = 0.7251

[[cities]]
id = "mannheim"
name = "Mannheim"
region = "southwest"
x = 0.3247
y = 0.7091

[[cities]]
id = "stuttgart"
name = "Stuttgart"
region = "southeast"
x = 0.3641
y = 0.7834

[[cities]]
id = "freiburg"
name = "Freiburg"
region = "southeast"
x = 0.2486
y = 0.8568

[[cities]]
id = "konstanz"
name = "Konstanz"
region = "southeast"
x = 0.3631
y = 0.8983

[[cities]]
id = "augsburg"
name = "Augsburg"
region = "southeast"
x = 0.5261
y = 0.8095

[[cities]]
id = "muenchen"
name = "München"
region = "southeast"
x = 0.6247
y = 0.8579

[[cities]]
id = "regensburg"
name = "Regensburg"
region = "southeast"
x = 0.6569
y = 0.7487

[[cities]]
id = "nuernberg"
name = "Nürnberg"
region = "southeast"
x = 0.5787
y = 0.6913

[[cities]]
id = "wuerzburg"
name = "Würzburg"
region = "east"
x = 0.4679
y = 0.6536

[[cities]]
id = "erfurt"
name = "Erfurt"
region = "east"
x = 0.5782
y = 0.5018

[[cities]]
id = "halle"
name = "Halle"
region = "east"
x = 0.6526
y = 0.4389

[[cities]]
id = "leipzig"
name = "Leipzig"
region = "east"
x = 0.7059
y = 0.4646

[[cities]]
id = "dresden"
name = "Dresden"
region = "east"
x = 0.8441
y = 0.5056

[[cities]]
id = "magdeburg"
name = "Magdeburg"
region = "northeast"
x = 0.6353
y = 0.3441

[[cities]]
id = "berlin"
name = "Berlin"
region = "northeast"
x = 0.7820
y = 0.3145

[[cities]]
id = "schwerin"
name = "Schwerin"
region = "northeast"
x = 0.5975
y = 0.1910

[[cities]]
id = "rostock"
name = "Rostock"
region = "northeast"
x = 0.6560
y = 0.1117

[[cities]]
id = "wilhelmshaven"
name = "Wilhelmshaven"
region = "northwest"
x = 0.2632
y = 0.1971

[[cities]]
id = "cuxhaven"
name = "Cuxhaven"
region = "northwest"
x = 0.3295
y = 0.1568

[[cities]]
id = "luebeck"
name = "Lübeck"
region = "northeast"
x = 0.5260
y = 0.1399

[[cities]]
id = "torgelow"
name = "Torgelow"
region = "northeast"
x = 0.8398
y = 0.1951

[[cities]]
id = "frankfurt_oder"
name = "Frankfurt (Oder)"
region = "northeast"
x = 0.8855
y = 0.3430

[[cities]]
id = "fulda"
name = "Fulda"
region = "east"
x = 0.4441
y = 0.5564

[[cities]]
id = "passau"
name = "Passau"
region = "east"
x = 0.8043
y = 0.7968

[[connections]]
from = "flensburg"
to = "kiel"
cost = 4

[[connections]]
from = "flensburg"
to = "hamburg"
cost = 8

[[connections]]
from = "kiel"
to = "hamburg"
cost = 8

[[connections]]
from = "hamburg"
to = "schwerin"
cost = 8

[[connections]]
from = "hamburg"
to = "bremen"
cost = 11

[[connections]]
from = "hamburg"
to = "hannover"
cost = 17

[[connections]]
from = "schwerin"
to = "rostock"
cost = 6

[[connections]]
from = "schwerin"
to = "magdeburg"
cost = 16

[[connections]]
from = "schwerin"
to = "berlin"
cost = 18

[[connections]]
from = "rostock"
to = "berlin"
cost = 18

[[connections]]
from = "bremen"
to = "hannover"
cost = 10

[[connections]]
from = "bremen"
to = "osnabrueck"
cost = 11

[[connections]]
from = "hannover"
to = "magdeburg"
cost = 15

[[connections]]
from = "hannover"
to = "dortmund"
cost = 18

[[connections]]
from = "hannover"
to = "kassel"
cost = 15

[[connections]]
from = "osnabrueck"
to = "muenster"
cost = 7

[[connections]]
from = "muenster"
to = "dortmund"
cost = 2

[[connections]]
from = "dortmund"
to = "duisburg"
cost = 4

[[connections]]
from = "dortmund"
to = "essen"
cost = 2

[[connections]]
from = "dortmund"
to = "duesseldorf"
cost = 6

[[connections]]
from = "duisburg"
to = "essen"
cost = 0

[[connections]]
from = "duisburg"
to = "duesseldorf"
cost = 2

[[connections]]
from = "essen"
to = "duesseldorf"
cost = 2

[[connections]]
from = "duesseldorf"
to = "koeln"
cost = 4

[[connections]]
from = "duesseldorf"
to = "aachen"
cost = 9

[[connections]]
from = "koeln"
to = "aachen"
cost = 7

[[connections]]
from = "koeln"
to = "trier"
cost = 20

[[connections]]
from = "koeln"
to = "frankfurt"
cost = 21

[[connections]]
from = "aachen"
to = "trier"
cost = 19

[[connections]]
from = "trier"
to = "saarbruecken"
cost = 11

[[connections]]
from = "trier"
to = "wiesbaden"
cost = 18

[[connections]]
from = "saarbruecken"
to = "mannheim"
cost = 11

[[connections]]
from = "saarbruecken"
to = "stuttgart"
cost = 17

[[connections]]
from = "frankfurt"
to = "wiesbaden"
cost = 0

[[connections]]
from = "frankfurt"
to = "kassel"
cost = 13

[[connections]]
from = "frankfurt"
to = "wuerzburg"
cost = 13

[[connections]]
from = "frankfurt"
to = "mannheim"
cost = 14

[[connections]]
from = "wiesbaden"
to = "mannheim"
cost = 11

[[connections]]
from = "mannheim"
to = "stuttgart"
cost = 6

[[connections]]
from = "mannheim"
to = "nuernberg"
cost = 22

[[connections]]
from = "stuttgart"
to = "freiburg"
cost = 16

[[connections]]
from = "stuttgart"
to = "augsburg"
cost = 16

[[connections]]
from = "freiburg"
to = "konstanz"
cost = 14

[[connections]]
from = "konstanz"
to = "augsburg"
cost = 17

[[connections]]
from = "augsburg"
to = "muenchen"
cost = 6

[[connections]]
from = "augsburg"
to = "nuernberg"
cost = 18

[[connections]]
from = "muenchen"
to = "regensburg"
cost = 10

[[connections]]
from = "muenchen"
to = "nuernberg"
cost = 21

[[connections]]
from = "regensburg"
to = "nuernberg"
cost = 12

[[connections]]
from = "nuernberg"
to = "wuerzburg"
cost = 8

[[connections]]
from = "wuerzburg"
to = "erfurt"
cost = 19

[[connections]]
from = "kassel"
to = "erfurt"
cost = 15

[[connections]]
from = "kassel"
to = "magdeburg"
cost = 21

[[connections]]
from = "erfurt"
to = "halle"
cost = 6

[[connections]]
from = "erfurt"
to = "leipzig"
cost = 8

[[connections]]
from = "halle"
to = "magdeburg"
cost = 11

[[connections]]
from = "halle"
to = "leipzig"
cost = 0

[[connections]]
from = "leipzig"
to = "dresden"
cost = 13

[[connections]]
from = "magdeburg"
to = "berlin"
cost = 10

[[connections]]
from = "berlin"
to = "dresden"
cost = 16

[[connections]]
from = "wilhelmshaven"
to = "bremen"
cost = 11

[[connections]]
from = "wilhelmshaven"
to = "cuxhaven"
cost = 10

[[connections]]
from = "cuxhaven"
to = "hamburg"
cost = 11

[[connections]]
from = "luebeck"
to = "hamburg"
cost = 6

[[connections]]
from = "luebeck"
to = "schwerin"
cost = 6

[[connections]]
from = "luebeck"
to = "kiel"
cost = 8

[[connections]]
from = "torgelow"
to = "rostock"
cost = 14

[[connections]]
from = "torgelow"
to = "schwerin"
cost = 11

[[connections]]
from = "frankfurt_oder"
to = "berlin"
cost = 6

[[connections]]
from = "frankfurt_oder"
to = "cottbus"
cost = 6

[[connections]]
from = "cottbus"
to = "dresden"
cost = 13

[[connections]]
from = "cottbus"
to = "leipzig"
cost = 21

[[connections]]
from = "gera"
to = "erfurt"
cost = 8

[[connections]]
from = "gera"
to = "leipzig"
cost = 8

[[connections]]
from = "gera"
to = "dresden"
cost = 19

[[resource_slots]]
resource = "coal"
index = 0
x = 0.0497
y = 0.9341

[[resource_slots]]
resource = "coal"
index = 1
x = 0.0799
y = 0.9337

[[resource_slots]]
resource = "coal"
index = 2
x = 0.1143
y = 0.9340

[[resource_slots]]
resource = "coal"
index = 3
x = 0.1552
y = 0.9332

[[resource_slots]]
resource = "coal"
index = 4
x = 0.1863
y = 0.9354

[[resource_slots]]
resource = "coal"
index = 5
x = 0.2210
y = 0.9365

[[resource_slots]]
resource = "coal"
index = 6
x = 0.2625
y = 0.9321

[[resource_slots]]
resource = "coal"
index = 7
x = 0.2941
y = 0.9340

[[resource_slots]]
resource = "coal"
index = 8
x = 0.3259
y = 0.9338

[[resource_slots]]
resource = "coal"
index = 9
x = 0.3697
y = 0.9347

[[resource_slots]]
resource = "coal"
index = 10
x = 0.4008
y = 0.9327

[[resource_slots]]
resource = "coal"
index = 11
x = 0.4316
y = 0.9336

[[resource_slots]]
resource = "coal"
index = 12
x = 0.4762
y = 0.9340

[[resource_slots]]
resource = "coal"
index = 13
x = 0.5067
y = 0.9340

[[resource_slots]]
resource = "coal"
index = 14
x = 0.5413
y = 0.9340

[[resource_slots]]
resource = "coal"
index = 15
x = 0.5834
y = 0.9340

[[resource_slots]]
resource = "coal"
index = 16
x = 0.6165
y = 0.9343

[[resource_slots]]
resource = "coal"
index = 17
x = 0.6469
y = 0.9351

[[resource_slots]]
resource = "coal"
index = 18
x = 0.6892
y = 0.9351

[[resource_slots]]
resource = "coal"
index = 19
x = 0.7187
y = 0.9341

[[resource_slots]]
resource = "coal"
index = 20
x = 0.7519
y = 0.9348

[[resource_slots]]
resource = "coal"
index = 21
x = 0.7941
y = 0.9352

[[resource_slots]]
resource = "coal"
index = 22
x = 0.8291
y = 0.9367

[[resource_slots]]
resource = "coal"
index = 23
x = 0.8588
y = 0.9351

[[resource_slots]]
resource = "oil"
index = 0
x = 0.0443
y = 0.9516

[[resource_slots]]
resource = "oil"
index = 1
x = 0.0689
y = 0.9504

[[resource_slots]]
resource = "oil"
index = 2
x = 0.0935
y = 0.9515

[[resource_slots]]
resource = "oil"
index = 3
x = 0.1514
y = 0.9534

[[resource_slots]]
resource = "oil"
index = 4
x = 0.1754
y = 0.9529

[[resource_slots]]
resource = "oil"
index = 5
x = 0.1963
y = 0.9529

[[resource_slots]]
resource = "oil"
index = 6
x = 0.2579
y = 0.9552

[[resource_slots]]
resource = "oil"
index = 7
x = 0.2836
y = 0.9518

[[resource_slots]]
resource = "oil"
index = 8
x = 0.3042
y = 0.9518

[[resource_slots]]
resource = "oil"
index = 9
x = 0.3643
y = 0.9520

[[resource_slots]]
resource = "oil"
index = 10
x = 0.3901
y = 0.9523

[[resource_slots]]
resource = "oil"
index = 11
x = 0.4137
y = 0.9535

[[resource_slots]]
resource = "oil"
index = 12
x = 0.4724
y = 0.9529

[[resource_slots]]
resource = "oil"
index = 13
x = 0.4969
y = 0.9529

[[resource_slots]]
resource = "oil"
index = 14
x = 0.5188
y = 0.9516

[[resource_slots]]
resource = "oil"
index = 15
x = 0.5777
y = 0.9550

[[resource_slots]]
resource = "oil"
index = 16
x = 0.6037
y = 0.9531

[[resource_slots]]
resource = "oil"
index = 17
x = 0.6261
y = 0.9541

[[resource_slots]]
resource = "oil"
index = 18
x = 0.6853
y = 0.9550

[[resource_slots]]
resource = "oil"
index = 19
x = 0.7094
y = 0.9537

[[resource_slots]]
resource = "oil"
index = 20
x = 0.7316
y = 0.9528

[[resource_slots]]
resource = "oil"
index = 21
x = 0.7911
y = 0.9549

[[resource_slots]]
resource = "oil"
index = 22
x = 0.8141
y = 0.9549

[[resource_slots]]
resource = "oil"
index = 23
x = 0.8345
y = 0.9544

[[resource_slots]]
resource = "garbage"
index = 0
x = 0.0478
y = 0.9730

[[resource_slots]]
resource = "garbage"
index = 1
x = 0.0806
y = 0.9728

[[resource_slots]]
resource = "garbage"
index = 2
x = 0.1139
y = 0.9729

[[resource_slots]]
resource = "garbage"
index = 3
x = 0.1521
y = 0.9756

[[resource_slots]]
resource = "garbage"
index = 4
x = 0.1888
y = 0.9743

[[resource_slots]]
resource = "garbage"
index = 5
x = 0.2213
y = 0.9743

[[resource_slots]]
resource = "garbage"
index = 6
x = 0.2616
y = 0.9743

[[resource_slots]]
resource = "garbage"
index = 7
x = 0.2935
y = 0.9727

[[resource_slots]]
resource = "garbage"
index = 8
x = 0.3258
y = 0.9727

[[resource_slots]]
resource = "garbage"
index = 9
x = 0.3694
y = 0.9743

[[resource_slots]]
resource = "garbage"
index = 10
x = 0.4026
y = 0.9732

[[resource_slots]]
resource = "garbage"
index = 11
x = 0.4327
y = 0.9720

[[resource_slots]]
resource = "garbage"
index = 12
x = 0.4746
y = 0.9720

[[resource_slots]]
resource = "garbage"
index = 13
x = 0.5072
y = 0.9720

[[resource_slots]]
resource = "garbage"
index = 14
x = 0.5403
y = 0.9720

[[resource_slots]]
resource = "garbage"
index = 15
x = 0.5819
y = 0.9720

[[resource_slots]]
resource = "garbage"
index = 16
x = 0.6172
y = 0.9710

[[resource_slots]]
resource = "garbage"
index = 17
x = 0.6476
y = 0.9736

[[resource_slots]]
resource = "garbage"
index = 18
x = 0.6899
y = 0.9726

[[resource_slots]]
resource = "garbage"
index = 19
x = 0.7218
y = 0.9723

[[resource_slots]]
resource = "garbage"
index = 20
x = 0.7527
y = 0.9723

[[resource_slots]]
resource = "garbage"
index = 21
x = 0.7937
y = 0.9723

[[resource_slots]]
resource = "garbage"
index = 22
x = 0.8262
y = 0.9723

[[resource_slots]]
resource = "garbage"
index = 23
x = 0.8601
y = 0.9719

[[resource_slots]]
resource = "uranium"
index = 0
x = 0.1146
y = 0.9520

[[resource_slots]]
resource = "uranium"
index = 1
x = 0.2211
y = 0.9526

[[resource_slots]]
resource = "uranium"
index = 2
x = 0.3287
y = 0.9524

[[resource_slots]]
resource = "uranium"
index = 3
x = 0.4341
y = 0.9538

[[resource_slots]]
resource = "uranium"
index = 4
x = 0.5426
y = 0.9545

[[resource_slots]]
resource = "uranium"
index = 5
x = 0.6502
y = 0.9550

[[resource_slots]]
resource = "uranium"
index = 6
x = 0.7534
y = 0.9523

[[resource_slots]]
resource = "uranium"
index = 7
x = 0.8637
y = 0.9518

[[resource_slots]]
resource = "uranium"
index = 8
x = 0.9042
y = 0.9357

[[resource_slots]]
resource = "uranium"
index = 9
x = 0.9470
y = 0.9371

[[resource_slots]]
resource = "uranium"
index = 10
x = 0.9055
y = 0.9705

[[resource_slots]]
resource = "uranium"
index = 11
x = 0.9460
y = 0.9721

[[turn_order_slots]]
index = 0
x = 0.0883
y = 0.0396

[[turn_order_slots]]
index = 1
x = 0.1252
y = 0.0404

[[turn_order_slots]]
index = 2
x = 0.1614
y = 0.0384

[[turn_order_slots]]
index = 3
x = 0.1987
y = 0.0400

[[turn_order_slots]]
index = 4
x = 0.2342
y = 0.0385

[[turn_order_slots]]
index = 5
x = 0.2699
y = 0.0397

[[city_tracker_slots]]
index = 0
x = 0.5093
y = 0.0375

[[city_tracker_slots]]
index = 1
x = 0.5595
y = 0.0371

[[city_tracker_slots]]
index = 2
x = 0.6317
y = 0.0381

[[city_tracker_slots]]
index = 3
x = 0.6946
y = 0.0399

[[city_tracker_slots]]
index = 4
x = 0.7687
y = 0.0387

[[city_tracker_slots]]
index = 5
x = 0.8340
y = 0.0367

[[city_tracker_slots]]
index = 6
x = 0.9058
y = 0.0390

[[city_tracker_slots]]
index = 7
x = 0.9537
y = 0.0390

[[city_tracker_slots]]
index = 8
x = 0.5108
y = 0.0704

[[city_tracker_slots]]
index = 9
x = 0.5464
y = 0.0704

[[city_tracker_slots]]
index = 10
x = 0.5763
y = 0.0704

[[city_tracker_slots]]
index = 11
x = 0.6140
y = 0.0704

[[city_tracker_slots]]
index = 12
x = 0.6456
y = 0.0704

[[city_tracker_slots]]
index = 13
x = 0.6806
y = 0.0704

[[city_tracker_slots]]
index = 14
x = 0.7144
y = 0.0704

[[city_tracker_slots]]
index = 15
x = 0.7487
y = 0.0704

[[city_tracker_slots]]
index = 16
x = 0.7818
y = 0.0694

[[city_tracker_slots]]
index = 17
x = 0.8199
y = 0.0708

[[city_tracker_slots]]
index = 18
x = 0.8528
y = 0.0703

[[city_tracker_slots]]
index = 19
x = 0.8859
y = 0.0692

[[city_tracker_slots]]
index = 20
x = 0.9234
y = 0.0692

[[city_tracker_slots]]
index = 21
x = 0.9535
y = 0.0682
