name = "Germany"
image = "germany.png"
regions = ["northwest", "northeast", "west", "east", "southwest", "southeast"]

[[cities]]
id = "flensburg"
name = "Flensburg"
region = "northwest"
x = 0.3981
y = 0.0433

[[cities]]
id = "kiel"
name = "Kiel"
region = "northwest"
x = 0.4498
y = 0.1008

[[cities]]
id = "hamburg"
name = "Hamburg"
region = "northwest"
x = 0.4466
y = 0.1952

[[cities]]
id = "bremen"
name = "Bremen"
region = "northwest"
x = 0.3486
y = 0.2514

[[cities]]
id = "hannover"
name = "Hannover"
region = "northwest"
x = 0.4512
y = 0.3374

[[cities]]
id = "dortmund"
name = "Dortmund"
region = "west"
x = 0.2338
y = 0.4538

[[cities]]
id = "duisburg"
name = "Duisburg"
region = "west"
x = 0.0831
y = 0.4105

[[cities]]
id = "essen"
name = "Essen"
region = "west"
x = 0.1444
y = 0.4253

[[cities]]
id = "duesseldorf"
name = "Düsseldorf"
region = "west"
x = 0.0989
y = 0.4816

[[cities]]
id = "koeln"
name = "Köln"
region = "southwest"
x = 0.1643
y = 0.5258

[[cities]]
id = "aachen"
name = "Aachen"
region = "southwest"
x = 0.0663
y = 0.5447

[[cities]]
id = "muenster"
name = "Münster"
region = "west"
x = 0.2172
y = 0.3857

[[cities]]
id = "osnabrueck"
name = "Osnabrück"
region = "west"
x = 0.2735
y = 0.3285

[[cities]]
id = "kassel"
name = "Kassel"
region = "west"
x = 0.4038
y = 0.4652

[[cities]]
id = "frankfurt"
name = "Frankfurt"
region = "southwest"
x = 0.3428
y = 0.5978

[[cities]]
id = "wiesbaden"
name = "Wiesbaden"
region = "southwest"
x = 0.2845
y = 0.6184

[[cities]]
id = "trier"
name = "Trier"
region = "southwest"
x = 0.1071
y = 0.6544

[[cities]]
id = "saarbruecken"
name = "Saarbrücken"
region = "southwest"
x = 0.1959
y = 0.7251

[[cities]]
id = "mannheim"
name = "Mannheim"
region = "southwest"
x = 0.3247
y = 0.7091

[[cities]]
id = "stuttgart"
name = "Stuttgart"
region = "southeast"
x = 0.3641
y = 0.7834

[[cities]]
id = "freiburg"
name = "Freiburg"
region = "southeast"
x = 0.2486
y = 0.8568

[[cities]]
id = "konstanz"
name = "Konstanz"
region = "southeast"
x = 0.3631
y = 0.8983

[[cities]]
id = "augsburg"
name = "Augsburg"
region = "southeast"
x = 0.5261
y = 0.8095

[[cities]]
id = "muenchen"
name = "München"
region = "southeast"
x = 0.6247
y = 0.8579

[[cities]]
id = "regensburg"
name = "Regensburg"
region = "southeast"
x = 0.6569
y = 0.7487

[[cities]]
id = "nuernberg"
name = "Nürnberg"
region = "east"
x = 0.5787
y = 0.6913

[[cities]]
id = "wuerzburg"
name = "Würzburg"
region = "east"
x = 0.4679
y = 0.6536

[[cities]]
id = "erfurt"
name = "Erfurt"
region = "east"
x = 0.5782
y = 0.5018

[[cities]]
id = "halle"
name = "Halle"
region = "east"
x = 0.6526
y = 0.4389

[[cities]]
id = "leipzig"
name = "Leipzig"
region = "east"
x = 0.7059
y = 0.4646

[[cities]]
id = "dresden"
name = "Dresden"
region = "east"
x = 0.8441
y = 0.5056

[[cities]]
id = "magdeburg"
name = "Magdeburg"
region = "northeast"
x = 0.6353
y = 0.3441

[[cities]]
id = "berlin"
name = "Berlin"
region = "northeast"
x = 0.7820
y = 0.3145

[[cities]]
id = "schwerin"
name = "Schwerin"
region = "northeast"
x = 0.5975
y = 0.1910

[[cities]]
id = "rostock"
name = "Rostock"
region = "northeast"
x = 0.6560
y = 0.1117

[[cities]]
id = "wilhelmshaven"
name = "Wilhelmshaven"
region = "northwest"
x = 0.2632
y = 0.1971

[[cities]]
id = "cuxhaven"
name = "Cuxhaven"
region = "northwest"
x = 0.3295
y = 0.1568

[[cities]]
id = "luebeck"
name = "Lübeck"
region = "northeast"
x = 0.5260
y = 0.1399

[[cities]]
id = "torgelow"
name = "Torgelow"
region = "northeast"
x = 0.8398
y = 0.1951

[[cities]]
id = "frankfurt_oder"
name = "Frankfurt (Oder)"
region = "northeast"
x = 0.8855
y = 0.3430

[[cities]]
id = "fulda"
name = "Fulda"
region = "east"
x = 0.4441
y = 0.5564

[[cities]]
id = "passau"
name = "Passau"
region = "southeast"
x = 0.8043
y = 0.7968

[[connections]]
from = "flensburg"
to = "kiel"
cost = 4

[[connections]]
from = "kiel"
to = "hamburg"
cost = 8

[[connections]]
from = "hamburg"
to = "schwerin"
cost = 8

[[connections]]
from = "hamburg"
to = "bremen"
cost = 11

[[connections]]
from = "hamburg"
to = "hannover"
cost = 17

[[connections]]
from = "schwerin"
to = "rostock"
cost = 6

[[connections]]
from = "schwerin"
to = "magdeburg"
cost = 16

[[connections]]
from = "schwerin"
to = "berlin"
cost = 18

[[connections]]
from = "bremen"
to = "hannover"
cost = 10

[[connections]]
from = "bremen"
to = "osnabrueck"
cost = 11

[[connections]]
from = "hannover"
to = "magdeburg"
cost = 15

[[connections]]
from = "hannover"
to = "kassel"
cost = 15

[[connections]]
from = "osnabrueck"
to = "muenster"
cost = 7

[[connections]]
from = "muenster"
to = "dortmund"
cost = 2

[[connections]]
from = "dortmund"
to = "essen"
cost = 4

[[connections]]
from = "duisburg"
to = "essen"
cost = 0

[[connections]]
from = "essen"
to = "duesseldorf"
cost = 2

[[connections]]
from = "duesseldorf"
to = "koeln"
cost = 4

[[connections]]
from = "duesseldorf"
to = "aachen"
cost = 9

[[connections]]
from = "koeln"
to = "aachen"
cost = 7

[[connections]]
from = "koeln"
to = "trier"
cost = 20

[[connections]]
from = "aachen"
to = "trier"
cost = 19

[[connections]]
from = "trier"
to = "saarbruecken"
cost = 11

[[connections]]
from = "trier"
to = "wiesbaden"
cost = 18

[[connections]]
from = "saarbruecken"
to = "mannheim"
cost = 11

[[connections]]
from = "saarbruecken"
to = "stuttgart"
cost = 17

[[connections]]
from = "frankfurt"
to = "wiesbaden"
cost = 0

[[connections]]
from = "frankfurt"
to = "kassel"
cost = 13

[[connections]]
from = "frankfurt"
to = "wuerzburg"
cost = 13

[[connections]]
from = "wiesbaden"
to = "mannheim"
cost = 11

[[connections]]
from = "mannheim"
to = "stuttgart"
cost = 6

[[connections]]
from = "stuttgart"
to = "freiburg"
cost = 16

[[connections]]
from = "stuttgart"
to = "augsburg"
cost = 15

[[connections]]
from = "freiburg"
to = "konstanz"
cost = 14

[[connections]]
from = "konstanz"
to = "augsburg"
cost = 17

[[connections]]
from = "augsburg"
to = "muenchen"
cost = 6

[[connections]]
from = "augsburg"
to = "nuernberg"
cost = 18

[[connections]]
from = "muenchen"
to = "regensburg"
cost = 10

[[connections]]
from = "regensburg"
to = "nuernberg"
cost = 12

[[connections]]
from = "nuernberg"
to = "wuerzburg"
cost = 8

[[connections]]
from = "kassel"
to = "erfurt"
cost = 15

[[connections]]
from = "erfurt"
to = "halle"
cost = 6

[[connections]]
from = "halle"
to = "magdeburg"
cost = 11

[[connections]]
from = "halle"
to = "leipzig"
cost = 0

[[connections]]
from = "leipzig"
to = "dresden"
cost = 13

[[connections]]
from = "magdeburg"
to = "berlin"
cost = 10

[[connections]]
from = "wilhelmshaven"
to = "bremen"
cost = 11

[[connections]]
from = "cuxhaven"
to = "hamburg"
cost = 11

[[connections]]
from = "luebeck"
to = "hamburg"
cost = 6

[[connections]]
from = "luebeck"
to = "schwerin"
cost = 6

[[connections]]
from = "luebeck"
to = "kiel"
cost = 4

[[connections]]
from = "torgelow"
to = "rostock"
cost = 19

[[connections]]
from = "torgelow"
to = "schwerin"
cost = 19

[[connections]]
from = "frankfurt_oder"
to = "berlin"
cost = 6

[[connections]]
from = "cuxhaven"
to = "bremen"
cost = 8

[[connections]]
from = "wilhelmshaven"
to = "osnabrueck"
cost = 14

[[connections]]
from = "muenster"
to = "essen"
cost = 6

[[connections]]
from = "essen"
to = "dortmund"
cost = 4

[[connections]]
from = "dortmund"
to = "koeln"
cost = 10

[[connections]]
from = "osnabrueck"
to = "hannover"
cost = 16

[[connections]]
from = "osnabrueck"
to = "kassel"
cost = 20

[[connections]]
from = "dortmund"
to = "kassel"
cost = 18

[[connections]]
from = "dortmund"
to = "frankfurt"
cost = 20

[[connections]]
from = "koeln"
to = "wiesbaden"
cost = 21

[[connections]]
from = "wiesbaden"
to = "saarbruecken"
cost = 10

[[connections]]
from = "stuttgart"
to = "konstanz"
cost = 16

[[connections]]
from = "muenchen"
to = "passau"
cost = 14

[[connections]]
from = "passau"
to = "regensburg"
cost = 12

[[connections]]
from = "regensburg"
to = "augsburg"
cost = 13

[[connections]]
from = "augsburg"
to = "wuerzburg"
cost = 19

[[connections]]
from = "wuerzburg"
to = "stuttgart"
cost = 12

[[connections]]
from = "wuerzburg"
to = "mannheim"
cost = 10

[[connections]]
from = "nuernberg"
to = "erfurt"
cost = 21

[[connections]]
from = "wuerzburg"
to = "fulda"
cost = 11

[[connections]]
from = "fulda"
to = "frankfurt"
cost = 8

[[connections]]
from = "fulda"
to = "kassel"
cost = 8

[[connections]]
from = "fulda"
to = "erfurt"
cost = 13

[[connections]]
from = "erfurt"
to = "hannover"
cost = 19

[[connections]]
from = "hannover"
to = "schwerin"
cost = 19

[[connections]]
from = "erfurt"
to = "dresden"
cost = 19

[[connections]]
from = "dresden"
to = "frankfurt_oder"
cost = 16

[[connections]]
from = "frankfurt_oder"
to = "leipzig"
cost = 21

[[connections]]
from = "halle"
to = "berlin"
cost = 17

[[connections]]
from = "berlin"
to = "torgelow"
cost = 15



